YusukeIwaki/playwright-ruby-client

lib/playwright/channel_owners/frame.rb
lib/playwright/channel_owners/page.rb
lib/playwright/connection.rb
lib/playwright/transport.rb
lib/playwright/utils.rb
spec/integration/page/autowaiting_basic_spec.rb
spec/spec_helper.rb

https://github.com/microsoft/playwright/blob/master/test/page-autowaiting-basic.spec.ts

Add page-autowaiting-basic.spec

---

.github/workflows/check.yml
.github/workflows/rspec.yml
README.md
development/generate_api.rb
development/generate_api/views/implemented_class_with_doc.rb
development/generate_api/views/implemented_class_without_doc.rb
development/generate_api/views/implemented_input_type_class.rb
development/generate_api/views/implemented_input_type_method.rb
development/generate_api/views/implemented_method_with_doc.rb
development/generate_api/views/implemented_proprerty_with_doc.rb
development/generate_api/views/unimplemented_class_with_doc.rb
development/generate_api/views/unimplemented_method_with_doc.rb
development/generate_api/views/unimplemented_property_with_doc.rb
docs/api_coverage.md
lib/playwright/channel_owners/frame.rb
lib/playwright/channel_owners/page.rb
spec/integration/example_spec.rb
spec/integration/page/autowaiting_basic_spec.rb
spec/integration/page/basic_spec.rb

Users want to know which API is alread available, and which one is not.

Add API implementation coverage

---

docs/api_coverage.md
lib/playwright/channel_owners/download.rb
spec/integration/download_spec.rb
spec/spec_helper.rb

Implement file downloading

---

docs/api_coverage.md
lib/playwright/channel_owners/binding_call.rb
lib/playwright/channel_owners/browser_context.rb
lib/playwright/channel_owners/page.rb
spec/integration/browser_context/basic_spec.rb

https://github.com/microsoft/playwright-python/blob/master/playwright/_impl/_browser_context.py
https://github.com/microsoft/playwright/blob/master/test/browsercontext-basic.spec.ts

Implement BrowserContext

---

docs/api_coverage.md
lib/playwright/channel_owners/browser_context.rb
lib/playwright/channel_owners/page.rb
lib/playwright/channel_owners/playwright.rb
lib/playwright/channel_owners/selectors.rb
spec/integration/selectorrs_spec.rb
spec/spec_helper.rb

```ruby
tag_selector = <<~JAVASCRIPT
{
query(root, selector) {
return root.querySelector(selector);
},
queryAll(root, selector) {
return Array.from(root.querySelectorAll(selector));
}
}
JAVASCRIPT
playwright.selectors.register('tag', script: tag_selector)
page.content = '<div><span></span></div><div></div>'
page.eval_on_selector('tag=DIV', '(e) => e.nodeName') # => 'DIV'
```

Implement Playwright::Selector

---

lib/playwright/connection.rb
lib/playwright/errors.rb
lib/playwright/transport.rb
spec/integration/element_handle/wait_for_element_state_spec.rb

Handle driver crash

---

docs/api_coverage.md
lib/playwright/channel_owners/browser.rb
spec/integration/tracing_spec.rb

resolves #51 
ref: https://github.com/microsoft/playwright-python/pull/611

Implement tracing

---

lib/playwright/channel.rb
lib/playwright/channel_owners/browser.rb
lib/playwright/channel_owners/browser_type.rb
spec/playwright/chromium_spec.rb

Implement BrowserType#connect_over_cdp

---

lib/playwright/channel_owners/element_handle.rb
spec/integration/page/check_spec.rb

fix ElementHandle#check and ElementHandle#uncheck to work

---

lib/playwright/playwright_api.rb
lib/playwright/transport.rb

I'm now developing capybara driver with Playwright. Some bugs are found during development.

For capybara integration

---

lib/playwright/transport.rb

This request addresses two issues:
1.
Currently only ASCII chars are working for method "fill". 
The reason has been using size instead of bytes.length which lead to playwright driver error if msg had longer byte size than advised before.
This change will allow also multiple byte chars in UTF-8 for fill.
2.
Larger values for fill or selectors lead to "Encoding::UndefinedConversionError: "\x.." from ASCII-8BIT to UTF-8" if the message length became longer than 128.
If @stdin file ist set to bin mode than also larger integer values may be transferred without conversion errors.
This change fixed the problems I had with UTF-8 and larger element IDs, but may be I haven't yet recognised the whole picture.

fill with all UTF-8 chars and longer selectors

---

playwright.gemspec

refs #73 
This Gem works with Ruby >= 2.4

Set required_ruby_version >= 2.4

---

lib/playwright/input_files.rb

Stop sending mimeTypes on setInputFiles

---

development/generate_api/example_codes.rb
documentation/docs/api/browser_context.md

use SHA256 instead of MD5

---

lib/playwright/channel_owners/page.rb

Remove on_worker call from Page

---

development/generate_api/example_codes.rb
development/unimplemented_examples.md
documentation/docs/api/route.md
spec/integration/example_spec.rb

add examples in documentation for Route

---

documentation/docs/api/web_socket.md
documentation/docs/include/api_coverage.md
lib/playwright/channel_owners/web_socket.rb

Add blank implementation of WebSocket for avoiding NameError

---

documentation/docs/article/guides/launch_browser.md
documentation/docs/article/guides/semi_automation.md

Add documentation about semi-automation

---

development/generate_api/renderers/apidoc_renderer.rb
documentation/docs/api/page.md
documentation/docs/api/web_socket.md
documentation/docs/include/api_coverage.md
lib/playwright/channel_owners/page.rb
lib/playwright/channel_owners/web_socket.rb
playwright.gemspec
spec/integration/web_socket_spec.rb
spec/spec_helper.rb

ref: https://github.com/microsoft/playwright-python/blob/master/playwright/_impl/_network.py
https://github.com/microsoft/playwright/blob/master/tests/web-socket.spec.ts
https://github.com/microsoft/playwright-python/blob/master/tests/async/test_websocket.py

implement WebSocket

---

.circleci/config.yml
development/generate_api/example_codes.rb
development/generate_api/renderers/apidoc_renderer.rb
development/unimplemented_examples.md
documentation/docs/api/browser.md
documentation/docs/api/browser_context.md
documentation/docs/api/cdp_session.md
documentation/docs/include/api_coverage.md
lib/playwright/channel_owners/browser.rb
lib/playwright/channel_owners/browser_context.rb
lib/playwright/channel_owners/cdp_session.rb
lib/playwright/channel_owners/response.rb
spec/integration/chromium/session_spec.rb
spec/integration/example_spec.rb

Since `.send` is reserved by Ruby,  use`.send_message` instead.

Implement CDPSession

---

lib/playwright/channel_owners/browser_context.rb
lib/playwright/channel_owners/page.rb
spec/integration/browser_context/route_spec.rb
spec/integration/page/route_spec.rb

JS: https://github.com/microsoft/playwright/pull/7585/files
Python: https://github.com/microsoft/playwright-python/pull/804/files

reverse route handlers order

---

documentation/docs/api/touchscreen.md
documentation/docs/include/api_coverage.md
lib/playwright/touchscreen_impl.rb
spec/integration/tap_spec.rb

ref: https://playwright.dev/docs/api/class-touchscreen/

Implement Touchscreen

---

documentation/docs/api/browser_context.md
documentation/docs/include/api_coverage.md
lib/playwright/channel_owners/browser_context.rb
spec/integration/browser_context/storage_state_spec.rb

https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state

Implement BrowserContext#storage_state

---

documentation/docs/api/browser_context.md
documentation/docs/api/page.md
documentation/docs/api/worker.md
documentation/docs/include/api_coverage.md
lib/playwright/channel_owners/browser_context.rb
lib/playwright/channel_owners/page.rb
lib/playwright/channel_owners/worker.rb
spec/integration/chromium_spec.rb
spec/integration/page/workers_spec.rb

https://playwright.dev/docs/api/class-worker/

Implement Worker

---

lib/playwright/channel.rb
lib/playwright/connection.rb
lib/playwright/transport.rb
lib/playwright/web_socket_transport.rb

Attach metadata on method call

---

spec/spec_helper.rb

Allow stopping RSpec execution by Ctrl+C

---

lib/playwright/transport.rb

fix: Prevent SIGINT to be passed into Playwright driver.

---

lib/playwright/transport.rb

Fix the Gem to work on Windows environment

---

lib/playwright/channel_owners/android.rb
lib/playwright/channel_owners/android_device.rb

fix AndroidDevice to work

---

lib/playwright/input_files.rb
spec/integration/example_spec.rb

Fix set_input_files to allow File parameter.

---

lib/playwright.rb
lib/playwright/channel_owners/android.rb
lib/playwright/channel_owners/android_device.rb
lib/playwright/channel_owners/playwright.rb
lib/playwright/web_socket_transport.rb

Prepare a server,
```js
const playwright = require('playwright-core')
playwright._android.launchServer({ port: 8000, wsPath: '/my-android' }).then(async server => {
console.log(`waiting on ${server.wsEndpoint()}`)
})
```
and connect to it via WebSocket
```ruby
require 'bundler/setup'
require 'playwright'
Playwright.connect_to_android_server('ws://127.0.0.1:8000/my-android') do |device|
device.launch_browser do |browser_context|
page = browser_context.new_page
page.goto('https://github.com/YusukeIwaki')
page.screenshot(path: 'YusukeIwaki.browser.png')
device.screenshot(path: 'YusukeIwaki.device.png')
end
end
```

Fix android device

---

development/generate_api/example_codes.rb
documentation/docs/api/locator.md
documentation/docs/include/api_coverage.md
lib/playwright/locator_impl.rb
spec/integration/page/locator/list_spec.rb

ref: https://github.com/microsoft/playwright/pull/19461, https://github.com/microsoft/playwright/issues/11909

feat(api): introduce Locator.all

---

lib/playwright/locator_utils.rb

👋 Thanks so much for this project!

Remove stray log line

---

documentation/docs/article/guides/playwright_on_alpine_linux.md
lib/playwright.rb
lib/playwright/channel_owners/playwright.rb
spec/remote/connect_to_browser_server_spec.rb

Fix Playwright.connect_to_browser_server to work

---

documentation/docs/article/guides/rails_integration.md
documentation/docusaurus.config.js
documentation/package.json
documentation/yarn.lock

also including upgrade docusaurus to v3. 
capybara-playwright-driver 0.5.0 comes with the feature of tracing.
https://rubygems.org/gems/capybara-playwright-driver/versions/0.5.0

Add guide for tracing.

---

lib/playwright/connection.rb

`metadata` in `async_send_message_to_server` could be nil, so I added nil check.

Add nil check to async_send_message_to_server

---

documentation/docusaurus.config.js
documentation/package.json
documentation/yarn.lock

resolves https://github.com/YusukeIwaki/playwright-ruby-client/issues/282
|before|after|
|:---|:---|
|![CleanShot 2024-03-07 at 00 46 28@2x](https://github.com/YusukeIwaki/playwright-ruby-client/assets/11763113/fa1daf0e-d9cf-45e4-ae83-12559673d49a)|![CleanShot 2024-03-07 at 00 47 01@2x](https://github.com/YusukeIwaki/playwright-ruby-client/assets/11763113/79336424-58b7-4844-a15f-4eeee676d1bf)<br/>![CleanShot 2024-03-07 at 00 40 08@2x](https://github.com/YusukeIwaki/playwright-ruby-client/assets/11763113/d072d000-14e9-46cd-ada6-a13b54dc73f7)|

Upgrade docusaurus to 3.1.1 and introduce algolia search.

---

lib/playwright/waiter.rb
spec/integration/page/wait_for_load_state_spec.rb

resolves #285 
resolves https://github.com/YusukeIwaki/capybara-playwright-driver/issues/72

Fix issue waitForEventInfo called twice.

---

lib/playwright/connection.rb
lib/playwright/transport.rb
lib/playwright/web_socket_transport.rb

cleanup on driver closed

---

lib/playwright/locator_assertions_impl.rb
spec/integration/assertions_spec.rb

Fix LocatorAssertions#to_be_in_viewport to work as expected

---

development/generate_api/models/method_aliasing.rb
documentation/docs/api/frame.md
documentation/docs/api/frame_locator.md
documentation/docs/api/locator.md
documentation/docs/api/page.md
spec/integration/page/selectors/get_by_spec.rb

alias get_by_test_id
