YusukeIwaki/playwright-ruby-client

.github/workflows/rspec.yml
`circleci/ruby:xxxx-node-browsers` image is really useful, but WebKit test cannot be executed on it.
Use native setup-node, setup-ruby. ref: https://github.com/microsoft/playwright/blob/master/.github/workflows/tests.yml
=> Use ubuntu-latest, setup-node, setup-ruby instead of container

.github/workflows/rspec.yml, lib/playwright/channel_owners/webkit_browser.rb, spec/integration/page/autowaiting_basic_spec.rb, spec/integration/page/basic_spec.rb, spec/integration/spec_helper_spec.rb, spec/spec_helper.rb
Now spec_helper detect target browser by 'BROWSER' environment variables.
Also, `chromium?` `firefox?` `webkit?` helper methods are defined.
=> Testing also with WebKit

spec/integration/page/basic_spec.rb
```
RECV>{"guid"=>"BrowserContext@7949e9bc91d30eee1e79fecdc8b1cee7", "method"=>"__create__", "params"=>{"type"=>"Page", "initializer"=>{"mainFrame"=>{"guid"=>"Frame@e062d6083c53be0ce7d9ea1721382b83"}, "viewportSize"=>{"width"=>1280, "height"=>720}, "isClosed"=>false}, "guid"=>"Page@33bfaaf2c3063e5315ef21c251871617"}}
RECV>{"guid"=>"BrowserContext@7949e9bc91d30eee1e79fecdc8b1cee7", "method"=>"page", "params"=>{"page"=>{"guid"=>"Page@33bfaaf2c3063e5315ef21c251871617"}}}
RECV>{"id"=>3, "result"=>{"page"=>{"guid"=>"Page@33bfaaf2c3063e5315ef21c251871617"}}}
SEND>{:id=>4, :guid=>"Page@33bfaaf2c3063e5315ef21c251871617", :method=>"close", :params=>{}}
SEND>{:id=>5, :guid=>"Frame@e062d6083c53be0ce7d9ea1721382b83", :method=>"evaluateExpression", :params=>{:expression=>"() => new Promise(r => {})", …
```
=> fix flaky spec

development/generate_api.rb, lib/playwright/channel_owners/android.rb, lib/playwright/channel_owners/android_device.rb, lib/playwright/channel_owners/browser.rb, lib/playwright/channel_owners/page.rb, lib/playwright/utils.rb
ref: https://github.com/microsoft/playwright/issues/1122, https://www.npmjs.com/package/playwright-android
Android automation components are already merged into playwright server, and available via playwright driver. So we can play with it also in Ruby :)
```ruby
require 'playwright'
Playwright.create(playwright_cli_executable_path: ENV['PLAYWRIGHT_CLI_EXECUTABLE_PATH']) do |playwright|
devices = playwright.android.devices
unless devices.empty?
device = devices.last
begin
puts "Model: #{device.model}"
puts "Serial: #{device.serial}"
puts device.shell('ls /system')
device.launch_browser do |context|
page = context.pages.first
page.goto('https://github.com/YusukeIwaki')
page.click('header button')
page.click('input[name="q"]')
page.keyboard.type_text('puppeteer')
page.expect_navigation { …
```
=> Implement Android Browser automation

README.md, development/generate_api.rb, development/generate_api/views/implemented_input_type_class_with_doc.rb, development/generate_api/views/implemented_input_type_class_without_doc.rb, lib/playwright/channel_owners/android_device.rb, lib/playwright/input_types/android_input.rb
Enjoy with native-Android automation :)
```ruby
require 'playwright'
Playwright.create(playwright_cli_executable_path: './node_modules/.bin/playwright') do |playwright|
devices = playwright.android.devices
unless devices.empty?
device = devices.last
begin
device.shell('input keyevent POWER')
device.shell('input keyevent POWER')
device.shell('input keyevent 82')
sleep 1
device.shell('cmd statusbar expand-notifications')
device.tap_on(res: 'com.android.systemui:id/clock')
ensure
device.close
end
end
end
```
=> implement AndroidDevice#tree, info, tap_on

development/generate_api/models/arg_doc.rb, development/generate_api/models/class_doc.rb, development/generate_api/models/doc.rb, development/generate_api/models/event_doc.rb, development/generate_api/models/method_doc.rb, development/generate_api/models/property_doc.rb, development/generate_api/views/documented_method_args.rb, docs/api_coverage.md, lib/playwright/channel_owner.rb, lib/playwright/channel_owners/android.rb, lib/playwright/channel_owners/android_device.rb, lib/playwright/channel_owners/browser.rb, lib/playwright/channel_owners/browser_context.rb, lib/playwright/channel_owners/element_handle.rb, lib/playwright/channel_owners/frame.rb, lib/playwright/channel_owners/js_handle.rb, lib/playwright/channel_owners/page.rb, lib/playwright/channel_owners/request.rb, lib/playwright/select_option_values.rb, lib/playwright/utils.rb, spec/development/generate_api/views/implemented_class_with_doc_spec.rb, spec/integration/page/basic_spec.rb, spec/integration/page/set_input_files_spec.rb
Some method definition was strange such as:
```
page.expect_event(Playwright::Events::Page::FileChooser, optionsOrPredicate: { timeout: 10 })
```
It would be better to describe them with simple optional parameters like Python
```
page.expect_event(Playwright::Events::Page::FileChooser, timeout: 10)
```
=> Migrate classes/methods code generation with Python's API specs

docs/api_coverage.md, lib/playwright/channel_owners/page.rb, spec/integration/download_spec.rb, spec/integration/page/set_input_files_spec.rb
playwright-python introduces some alias methods for `expect_event('download')` `expect_event('file_chooser')` and so on.
Let's use them also in playwright-ruby-client
=> Implement expext_xxx APIs fpr Playwright::Page

.github/workflows/windows_check.yml, spec/integration/example_spec.rb
playwright-ruby-client is already windows-compatible.
However some specs are incompatible...
=> Make playwright-ruby-client Windows-compatible

lib/playwright/channel_owners/playwright.rb, spec/integration/browser_context/device_spec.rb
Allow device emulation like playwright-python.
```ruby
require 'playwright'
Playwright.create(playwright_cli_executable_path: ENV['PLAYWRIGHT_CLI_EXECUTABLE_PATH']) do |playwright|
iPhone = playwright.devices['iPhone 6']
playwright.chromium.launch(headless: false) do |browser|
page = browser.new_page(**iPhone)
page.goto("https://ifconfig.me/ua")
puts page.evaluate('() => document.body.textContent') # => Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
end
end
```
=> Add spec for playwright.devices

.circleci/config.yml, .github/workflows/windows_check.yml, README.md, lib/playwright/transport.rb
In browser automation, most users prefer `npx playwright` instead of installing playwright locally.
So enable us to specify `playwright_cli_executable_path: 'npx playwright'` :)
=> Allow using npx for playwright_cli_executable_path

development/generate_api/views/documented_method_args.rb, development/generate_api/views/undocumented_method_args.rb, lib/playwright.rb, lib/playwright/async_evaluation.rb, lib/playwright/async_value.rb, lib/playwright/channel.rb, lib/playwright/connection.rb, lib/playwright/transport.rb, lib/playwright/wait_helper.rb, playwright.gemspec, spec/integration/browser_context/device_spec.rb, spec/integration/browser_context/route_spec.rb, spec/integration/element_handle/wait_for_element_state_spec.rb, spec/integration/page/autowaiting_basic_spec.rb, spec/integration/page/basic_spec.rb, spec/integration/page/dialog_spec.rb, spec/integration/page/route_spec.rb, spec/integration/page/set_input_files_spec.rb, spec/integration/page/wait_for_function_spec.rb, spec/playwright/async_evaluation_spec.rb, spec/playwright/async_value_spec.rb, spec/spec_helper.rb
concurrent-ruby uses Thead for concurrent job execution. It often causes unexpected race condition, and we have to avoid it with `sleep 0.5` or something with best effot... It is really annoying.
playwright-ruby-client doesn't provide async APIs directly for users. So we can easily replace asynchrous architecture internally. Introduce https://github.com/socketry/async for better async. It is based on Fiber.
https://rubykaigi.org/2019/presentations/ioquatix.html
=> Introduce socketry/async instead of concurrent-ruby

spec/integration/download_spec.rb, spec/integration/page/autowaiting_basic_spec.rb, spec/sinatra_spec.rb, spec/spec_helper.rb
Sinatra::Base gives more priority to static routes than dynamic defined one.  So this definition below is ignored. This is inconvenient in our unit testing...
```
sinatra.get('/empty.html') { 'My Empty' }
```
Let's change the routing priority.
=> Allow overriding sinatra static routes

.github/workflows/rspec.yml
* Execute Integration tests only after unit test passed.
* Fix forgotten PLAYWRIGHT_CLI_EXECUTABLE_PATH setting
=> fix GitHub Actions

lib/playwright/channel_owner.rb, lib/playwright/playwright_api.rb, spec/integration/example_spec.rb
playwright-ruby-client uses generated API codes.
In current implementation, Playwright API instance is always generated for each channel owner reference.
So `page.context.pages.last` is not the same instance as `page`...
This implementation is not so good when extending Playwright::Page or Playwright::Browser.
This PR introduces the instance cache for Playwright API.
=> cache Playwright API instance

development/generate_api/example_codes.rb, development/generate_api/renderers/apidoc_renderer.rb, documentation/docs/api/browser_context.md
Officual Playwright documentation shows an example with `md5`. (ref: https://github.com/microsoft/playwright/pull/6805)
playwright-ruby-client documentation should be the same.
=> use md5 example instead of sha256

development/unimplemented_examples.md, documentation/docs/api/worker.md, documentation/docs/include/api_coverage.md, lib/playwright/channel_owners/binding_call.rb, lib/playwright/channel_owners/worker.rb, lib/playwright/playwright_api.rb, spec/integration/browser_context/expose_function_spec.rb
When the evaluation result is Playwright::JSHandle, it should be unwrapped.
=> fix expose_binding to work with ElementHandle

documentation/docs/article/guides/rails_integration.md
Node#drag_to is implemented partially in https://github.com/YusukeIwaki/capybara-playwright-driver/pull/33
=> Update Capybara guide

documentation/docs/api/browser.md, documentation/docs/api/browser_context.md, lib/playwright/channel_owners/browser.rb, lib/playwright/channel_owners/browser_context.rb, lib/playwright/channel_owners/browser_type.rb, spec/spec_helper.rb
refs https://github.com/microsoft/playwright-python/pull/746
```
playwright.chromium.launch do |browser|
browser.new_page do |page| # <--
end
end
```
=> allow Browser#new_page and BrowserContext#new_page to call with block for auto-closing

documentation/docs/api/browser_type.md, documentation/docs/include/api_coverage.md, lib/playwright/channel_owners/browser_type.rb, spec/integration/default_browser_context_spec.rb, spec/spec_helper.rb
Allow users to re-use a browser execution context.
ref: https://github.com/YusukeIwaki/playwright-ruby-client/issues/104#issuecomment-858286504
In most case it is not the best practice to re-use the execution context, but some users expect 'semi-automation' usage. (User authentication is manually done by hand, and then enjoy automation using the persisted login session)
https://stackoverflow.com/questions/61359929/start-browser-in-non-icognito-to-preserve-login
=> Implement BrowserType#launch_persistent_context

documentation/docs/api/page.md, documentation/docs/include/api_coverage.md, lib/playwright/channel_owners/page.rb, spec/integration/page/wait_for_request_finished_spec.rb
Playwright 1.12 introduced a new API `Page#expect_request_finished`.
Include it into playwright-ruby-client.
=> Implement Page#expect_request_finished

documentation/docs/article/guides/rails_integration.md
We can handle HTML5 drag/drop with Playwright 1.12.0 or later. (Special thanks to https://github.com/microsoft/playwright/pull/6207)
```ruby
it 'drag and drop' do
Capybara.app_host = 'https://www.w3schools.com'
visit '/html/html5_draganddrop.asp'
find('#drag1').drag_to(find('#div2'))
end
```
This example works as expected with latest Chrome.
However when we execute https://github.com/teamcapybara/capybara/blob/master/lib/capybara/spec/session/node_spec.rb, it doesn't works as Capybara expects...
```
#drag_to
HTML5
should HTML5 drag and drop an object
should HTML5 drag and drop an object child
should set clientX/Y in dragover events (FAILED - 1)
should preserve clientX/Y from last dragover event (FAILED - 2)
should not HTML5 drag and drop on a non HTML5 drop element
should HTML5 drag and …
```
=> update documentation about HTML5 drag of capybara driver

.circleci/config.yml, README.md, lib/playwright.rb, lib/playwright/connection.rb, lib/playwright/transport.rb, lib/playwright/web_socket.rb, lib/playwright/web_socket_client.rb, lib/playwright/web_socket_transport.rb, spec/spec_helper.rb
Playwright requires many dependencies for installing browsers and must be permitted to launch browser process via shell-exec.
Most web services developers would hesitate to allow web server to execute non-web (browser) process. Some other developers would have trouble with executing browser automation script on Alpine Linux.
By separating browser owners into Playwright server, Ruby environment can be more simple.
We can now easily integrate Playwright into Rails application.
=> [EXPERIMENTAL] connect via WebSocket

documentation/docs/api/page.md, documentation/docs/article/guides/inspector.md, documentation/docs/article/guides/playwright_on_alpine_linux.md, documentation/docs/article/guides/semi_automation.md, documentation/docs/include/api_coverage.md, lib/playwright/channel_owners/browser_context.rb, lib/playwright/channel_owners/page.rb, spec/integration/page/pause_spec.rb
`binding.pry` is enough in most cases, however Playwright inspector is helpful. Some users want to use it.
```ruby
playwright.chromium.launch(headless: false) do |browser|
browser.new_context do |context|
context.enable_debug_console!
page = context.new_pagè
page.goto('http://example.com/')
page.pause
end
end
```
=> Page#pause

lib/playwright.rb, lib/playwright/channel_owners/playwright.rb
`BrowserType#connect` is a method to connect to Browser server.
It requires playwright driver but not it is used in actual implementation. So in this library, the method is implemented as `Playwright#connect_to_browser_server`
ref: https://github.com/YusukeIwaki/playwright-python-remote/pull/2
server: (requires version after https://github.com/microsoft/playwright/pull/8353)
```js
const playwright = require('playwright')
option = {
channel: 'chrome-canary',
headless: false,
port: 8080,
wsPath: 'ws',
}
playwright.chromium.launchServer(option).then((server) => { console.log(server.wsEndpoint()) })
```
```ruby
Playwright.connect_to_browser_server('ws://127.0.0.1:8080/ws') do |browser|
page = browser.new_page
page.goto('https://github.com/YusukeIwaki')
page.screenshot(path: 'YusukeIwaki.png') …
```
=> Implement Playwright.connect_to_browser_server

development/generate_api/example_codes.rb, spec/integration/example_spec.rb
Fix flaky tests caused by unpredictable slow network.
=> retry network failure on example spec

lib/playwright/channel_owners/browser_context.rb, spec/integration/browser_context/clear_cookies_spec.rb
```
Playwright::Error:
Error: urls: expected array, got object
```
Found by https://github.com/YusukeIwaki/playwright-ruby-client/pull/208
=> fix BrowserContext#cookies to work

lib/playwright/channel_owners/browser_context.rb, lib/playwright/channel_owners/page.rb, spec/integration/browser_context/add_init_script_spec.rb, spec/integration/page/add_init_script_spec.rb
```
Failure/Error: async_send_message_to_server(guid, method, params, metadata: metadata).value!
Playwright::Error:
Error: source: expected string, got object
```
found by https://github.com/YusukeIwaki/playwright-ruby-client/pull/208
=> fix BrowserContext#add_init_script and Page#add_init_script to work

documentation/src/components/HomepageFeatures.js
Fixes minor typo on the doc homepage. Thanks for your work on this!
=> Fix typo in docs homepage (relyable -> reliable)

documentation/docs/article/guides/rails_integration.md
Adds serviceWorkers documentation to rails integration https://playwright-ruby-client.vercel.app/docs/api/browser#new_context
serviceWorkers is added as a page option to capybara-playwright-driver in this PR https://github.com/YusukeIwaki/capybara-playwright-driver/pull/53
=> Add serviceWorkers to rails integration documentation

development/generate_api/example_codes.rb, lib/playwright/channel_owners/browser_context.rb, lib/playwright/channel_owners/page.rb, lib/playwright/event_emitter.rb, spec/integration/page/dialog_spec.rb, spec/integration/page/response_misc_spec.rb, spec/integration/page/route_spec.rb
resolves #227 
As playwright-python uses AsyncIOEventEmitter, the callback of event emitter should be called as async.
However concurrent-ruby is not coroutine but thread-based. It would breaks the order of callback processing unexpectedly, so keep the change only for `response` and `dialog` events at this moment.
=> Make event emitter async for 'response' and 'dialog' event

development/generate_api/example_codes.rb, documentation/docs/api/dialog.md, lib/playwright/channel_owners/browser_context.rb, lib/playwright/channel_owners/page.rb, lib/playwright/event_emitter.rb, playwright.gemspec, spec/integration/page/dialog_spec.rb, spec/integration/page/response_misc_spec.rb, spec/integration/page/route_spec.rb
resolves #227 backport for 1.28.0
=> [1.28.1] Make event emitter async for 'response' and 'dialog' event

spec/integration/tracing_spec.rb
```
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2023-08-17 00:04:55 +0900 ===
- Goodbye!
should work with multiple chunks (FAILED - 1)
Failures:
1) tracing should work with multiple chunks
Failure/Error: @connection.local_utils.trace_discarded(@stacks_id)
NoMethodError:
undefined method `trace_discarded' for #<localUtils>
Did you mean?  tracing_discarded
```
```
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2023-08-17 00:11:20 +0900 ===
- Goodbye!
should work with multiple chunks
Finished in 19.11 seconds (files took 0.46779 seconds to load)
13 examples, 0 failures
```
=> Add a spec for reproducing #262

lib/playwright/channel.rb
This prevents the NoMethodError from occurring in irb.
=> Use the safe navigation operator for absolute_path

lib/playwright/locator_impl.rb, spec/integration/page/locator/list_spec.rb
This allows you to say `page.locator("a[href]").all.map { |a| a["href"] }` as a natural analogy from `page.locator("a#id[href]")["href"]`.
=> Alias [] to LocatorImpl#get_attribute

.gitignore, development/generate_api.rb, development/unimplemented_examples.md, documentation/docs/api/locator_assertions.md, documentation/docs/include/api_coverage.md, lib/playwright/errors.rb, lib/playwright/javascript/value_serializer.rb, lib/playwright/locator_assertions_impl.rb, lib/playwright/locator_impl.rb, lib/playwright/test.rb, spec/integration/locator_assertions_spec.rb
closes #268
This PR implements:
- Locator assertions API
- Expectations
- RSpec integration (and potentially Shoulda - but I haven't tested)
Potential future work:
- Page and API assertions APIs
- Minitest assertions
- Global configuration of expectations
Any feedback welcome
=> Implement Locator assertions

playwright.gemspec
https://github.com/YusukeIwaki/playwright-ruby-client/pull/277/commits/633019e208a766ef506a970e5ae6ab85e0324325 this commit broke the compatibility with Ruby 2.4, 2.5.
Fix it.
=> Fix CI flures on Ruby <= 2.5

documentation/docs/article/guides/rspec_integration.md
Update instructions to include Playwright::Test::Matchers vs Playwright::RSpec::Matchers (which doesn't exist).
Thanks for making it so easy to use playwright for browser testing a rails app!
=> Docs: Update rspec_integration.md

lib/playwright/locator_assertions_impl.rb, spec/playwright/locator_assertion_impl_spec.rb
If you accidentally provide a non-string/non-regex value to an assertion like `expect(page.get_by_label('Calculated Total').to have_value(1.25)` then you get a cryptic error
```
Playwright::Error:
expectedText[0]: expected object, got null
```
This change will provide a more helpful error message like
```
ArgumentError:
Expected value provided to assertion to be a string or regex, got Integer
```
=> throw ArgumentError when value provided to locator assertions is not a string or regex

lib/playwright/test.rb, spec/integration/assertions_spec.rb
```
Failures:
1) Playwright::LocatorAssertions#to_be_visible should work eventually when negated
Failure/Error: @failure_message.gsub("expected to", "not expected to")
NoMethodError:
undefined method `gsub` for nil
....
```
This error occurs when a matcher is negated via RSpec and initially does not pass the assertion.
Example:
```ruby
expect(page.locator("span")).not_to be_visible
```
If the page initially has a visible `span`, then `Expect.new.call(...)` will not raise an `AssertionError` and `#matches?` will return `true`. 
But RSpec expects `matches?` to be `false` for negated matchers and calls `#failure_message_when_negated` in that case, and `@failure_message` wasn't set so it crashes.
Use `#does_not_match?` to set `is_not` accurately
[RSpec …
=> fix: eventual negated matchers failure messages

lib/playwright/channel_owners/browser_context.rb
This [commit](https://github.com/microsoft/playwright/commit/418d1c0c5557c5ccabd87c440146ef9c0c5987aa#diff-d7c041137e763edae5c4d18bc8ded9a1ac668078e310712341c444ef3aac423bR496) (which is [part](https://github.com/microsoft/playwright/blob/v1.48.2/packages/playwright-core/src/client/browserContext.ts#L496) of v1.48.2, the [`COMPATIBLE_PLAYWRIGHT_VERSION`](https://github.com/YusukeIwaki/playwright-ruby-client/blob/cc37b97e1dae429a81ce3b3540e0fb2930bfe7be/lib/playwright/version.rb#L5)) changed an internal API which broke `page.context.enable_debug_console!`
=>  Bugfix: page.context.enable_debug_console! does not work after Playwright internal change

lib/playwright/clock_impl.rb
Hello! 
First of all, thank you for this Gem, it's really useful!
I noticed that when I set the time of the clock using something like
```rb
page.driver.with_playwright_page do |page|
page.clock.set_fixed_time(DateTime.parse("2022-01-01"))
end
```
then the browser is actually set to 1970.
```js
// Browser Console
new Date()
=> Tue Jan 20 1970 00:49:55 GMT+0100 (Central European Standard Time)
Date.now()
=> 1640995200
```
This is ALMOST correct, because we call this in Ruby:
```
DateTime.parse("2022-01-01").utc.to_i
=> 1640995200
```
But JavaScript is not counting seconds since 1970, but milliseconds. It needs to be multiplied with 1000, then it works. That's what this PR does.
Thank you for your consideration!
=> Convert time to milliseconds in `set_fixed_time`

lib/playwright/transport.rb
Hello.
The current code calls terminate on the return value wait_thread of Open3.popen3. wait_thread represents the management thread for calling wait/waitpid. When terminate is called, wait/waitpid will no longer be invoked.
On some AWS Lambda and Docker containers, the process with process id 1 does not clean up the process table. As a result, the node.js process becomes a zombie process.
Referring to the Open3.popen3 call to set block arguments, it seems correct to call join for wait_thread.
https://github.com/ruby/open3/blob/b8909222051b4103a19eba19506727faece252e7/lib/open3.rb#L533-L547
I have created a file to check the behavior in a local Docker container, which is attached.
[reproduction.zip](https://github.com/user-attachments/files/20861693/reproduction.zip)
Builds a container …
=> On AWS Lambda, node process become zombie process

documentation/docs/article/guides/playwright_on_alpine_linux.md, lib/playwright.rb, lib/playwright/channel_owners/browser_type.rb, lib/playwright/web_socket_client.rb, lib/playwright/web_socket_transport.rb, spec/remote/connect_to_android_server_spec.rb
before fix
```
Failures:
1) Playwright.connect_to_browser_server should work
Failure/Error: browser.send(:update_browser_type, self)
NoMethodError:
undefined method `update_browser_type' for #<browser@d4d05723817f70d904f5e7c7ff80cf58>
```
Resolves #346
=> Fix Playwright.connect_to_browser_server to work
